// <auto-generated />
using System;
using FFStats.Persistence;
using FFStats.Persistence.Contextos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FFStats.Persistence.Migrations
{
    [DbContext(typeof(FFStatsContext))]
    partial class FFStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.17");

            modelBuilder.Entity("FFStats.Domain.Models.Call", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("callCidade")
                        .HasColumnType("TEXT");

                    b.Property<int>("mapaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("mapaId");

                    b.ToTable("Calls");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Estatisticas", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assistencia")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Dano")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kill")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Ressucitado")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Salvador")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tempo")
                        .HasColumnType("INTEGER");

                    b.Property<int>("jogadorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("partidaId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("jogadorId");

                    b.HasIndex("partidaId");

                    b.ToTable("Estatisticas");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("jogadorNick")
                        .HasColumnType("TEXT");

                    b.Property<string>("jogadorNome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Mapa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("mapaNome")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mapas");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Modo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("modoDescricao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modos");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Partida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("callId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mapaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("modoId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("partidaData")
                        .HasColumnType("TEXT");

                    b.Property<string>("partidaDescricao")
                        .HasColumnType("TEXT");

                    b.Property<int>("posicao")
                        .HasColumnType("INTEGER");

                    b.Property<int>("submodoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("treinoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("callId");

                    b.HasIndex("mapaId");

                    b.HasIndex("modoId");

                    b.HasIndex("submodoId");

                    b.HasIndex("treinoId");

                    b.ToTable("Partidas");
                });

            modelBuilder.Entity("FFStats.Domain.Models.PartidaJogador", b =>
                {
                    b.Property<int>("PartidaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JogadorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PartidaId", "JogadorId");

                    b.HasIndex("JogadorId");

                    b.ToTable("PartidasJogadores");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Submodo", b =>
                {
                    b.Property<int>("submodoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("modoId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("submodoDescricao")
                        .HasColumnType("TEXT");

                    b.HasKey("submodoId");

                    b.HasIndex("modoId");

                    b.ToTable("Submodos");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Treino", b =>
                {
                    b.Property<int>("treinoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("treinoDescricao")
                        .HasColumnType("TEXT");

                    b.HasKey("treinoId");

                    b.ToTable("Treinos");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Call", b =>
                {
                    b.HasOne("FFStats.Domain.Models.Mapa", "mapa")
                        .WithMany()
                        .HasForeignKey("mapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mapa");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Estatisticas", b =>
                {
                    b.HasOne("FFStats.Domain.Models.Jogador", "Jogador")
                        .WithMany()
                        .HasForeignKey("jogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Partida", "Partida")
                        .WithMany()
                        .HasForeignKey("partidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Partida", b =>
                {
                    b.HasOne("FFStats.Domain.Models.Call", "call")
                        .WithMany()
                        .HasForeignKey("callId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Mapa", "mapa")
                        .WithMany()
                        .HasForeignKey("mapaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Modo", "modo")
                        .WithMany()
                        .HasForeignKey("modoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Submodo", "sumodo")
                        .WithMany()
                        .HasForeignKey("submodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Treino", "treino")
                        .WithMany()
                        .HasForeignKey("treinoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("call");

                    b.Navigation("mapa");

                    b.Navigation("modo");

                    b.Navigation("sumodo");

                    b.Navigation("treino");
                });

            modelBuilder.Entity("FFStats.Domain.Models.PartidaJogador", b =>
                {
                    b.HasOne("FFStats.Domain.Models.Jogador", "Jogador")
                        .WithMany("PartidasJogadores")
                        .HasForeignKey("JogadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FFStats.Domain.Models.Partida", "Partida")
                        .WithMany("PartidasJogadores")
                        .HasForeignKey("PartidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jogador");

                    b.Navigation("Partida");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Submodo", b =>
                {
                    b.HasOne("FFStats.Domain.Models.Modo", "modo")
                        .WithMany()
                        .HasForeignKey("modoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("modo");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Jogador", b =>
                {
                    b.Navigation("PartidasJogadores");
                });

            modelBuilder.Entity("FFStats.Domain.Models.Partida", b =>
                {
                    b.Navigation("PartidasJogadores");
                });
#pragma warning restore 612, 618
        }
    }
}
